### ISSUE TITLE
unable to export to html

### ISSUE THREAD

**Issue by bbgky** [pbugnion/gmaps#187] opened 2017-10-10 13:52 UTC
Hi
I was following 
http://jupyter-gmaps.readthedocs.io/en/latest/export.html#exporting-to-html
to export gmap to html,
but i got error like this once i run the `http://0.0.0.0:8080/export.html`
i couldn't get the map but exceptions.

Don't know where is the `jupyter-gmaps.js`

Thanks
```
python -m http.server 8080
Serving HTTP on 0.0.0.0 port 8080 (http://0.0.0.0:8080/) ...
127.0.0.1 - - [10/Oct/2017 15:42:31] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 15:42:35] "GET /export.html HTTP/1.1" 200 -
127.0.0.1 - - [10/Oct/2017 15:42:36] code 404, message File not found
127.0.0.1 - - [10/Oct/2017 15:42:36] "GET /jupyter-gmaps.js HTTP/1.1" 404 -
```

**Comment by pbugnion** [comment] 2017-10-10 17:25
Thanks for raising this. Can you post the contents of `export.html`?

**Comment by pbugnion** [comment] 2017-10-17 06:27
Any luck with this? I'm going to close this issue since I can't reproduce it, but feel free to re-open.

**Closed by pbugnion** 2017-10-17 06:27 UTC
