### ISSUE TITLE
Does not display output

### ISSUE THREAD

**Issue by Mohitsharma44** [pbugnion/gmaps#44] opened 2015-08-26 01:40 UTC
Running the following code does not produce any output on Ipython Notebook v3.2.0 and Python 2.7.10

```
import gmaps

data = [ [ 37.782551,-122.445368 ],
         [ 37.782745,-122.444586 ],
         [ 37.782842,-122.443858 ] ]

gmaps.heatmap(data)
```
No Warnings (except for 
`:0: FutureWarning: IPython widgets are experimental and may change in the future`.) and No Errors.

**Comment by pbugnion** [comment] 2015-08-31 13:20
I have just tried running this on v3.2.0, and it worked fine. Note that the import needs to be in its own cell -- this is a little idiosyncratic and unexpected, and I hope to be able to remove it in the future, but at the moment, the import injects the necessary javascript directly into the DOM.

**Comment by GuillermoArjun** [comment] 2015-09-08 10:17
Hi,

I'm having the same issue as OP - my system is IPython 3.2.1, Python 2,7.10, Anaconda 2.3.0

In [1]: import gmaps as gm

In [2]: taxi_data = gm.datasets.load_dataset('taxi_rides')
          taxi_data[:5]
          trial_map = gm.heatmap(taxi_data)
          gm.display(trial__map)

Same warning, tried importing just gmaps on it's on and still get no output.

Thanks,
Will

**Comment by pbugnion** [comment] 2015-09-08 15:12
What web browser are you using?

**Comment by Mohitsharma44** [comment] 2015-09-08 15:52
@pbugnion I did import gmaps separately in its own cell. It still spits the same error. 
I tried with Chrome, Firefox and Safari.

**Comment by pbugnion** [comment] 2015-09-08 16:07
@Mohitsharma44  Are you also using Anaconda?

**Comment by Mohitsharma44** [comment] 2015-09-08 16:08
No.
I am using regular python 2.7 and jupyter (homebrew and pip)

**Comment by pbugnion** [comment] 2015-09-08 16:11
Is this `gmaps` installed via pip, or the development version?

**Comment by Mohitsharma44** [comment] 2015-09-08 16:19
I installed it via pip.

**Comment by pbugnion** [comment] 2015-09-08 16:21
OK -- I'll have a look at this later tonight.

**Comment by pbugnion** [comment] 2015-09-08 21:02
Still struggling to reproduce this. It would be useful if you:

1. Opened a completely new notebook
2. Opened the Javascript console
3. Run the above code. After you've run `import gmaps`, the console ought to read something like `Loaded extension: gmaps_js/heatmap_view`. Nothing should appear in the console when you run `gmaps.heatmap(data)`
4. Let me know what errors crop up. 

Thanks a lot.

**Comment by lfiaschi** [comment] 2015-11-16 04:07
hi I have installed for python 3 after fixing some imports and try to run the heatmap notebook example. The layer gets created but do not displays itself. ipython version 4.0. Any idea what could be the problem?

**Comment by pbugnion** [comment] 2015-11-21 10:20
Just tried your PR with Python 3 and IPython 4.0.0 and everything displays fine:

<img width="1200" alt="screen shot 2015-11-21 at 10 17 52" src="https://cloud.githubusercontent.com/assets/1392879/11318000/7163174a-9039-11e5-8263-332c1d33fd5c.png">

**Comment by constcast** [comment] 2015-11-24 14:20
I have the same problem and can see the following errors in my JS console when I run the code above:

    GET http://localhost:8888/nbextensions/gmaps_js/heatmap_view.js [HTTP/1.1 404 Not Found 3ms]
    Failed to load extension(s): Array [ "nbextensions/gmaps_js/heatmap_view" ] Error: Script error for: nbextensions/gmaps_js/heatmap_view
    http://requirejs.org/docs/errors.html#scripterror
    Stack trace:
    makeError@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:166:17
    newContext/context.onScriptError@http://localhost:8888/static/components/requirejs/require.js?v=640929dac3c23a448d2eebc37bc32062:1689:36

Does this point to an installation error?

**Comment by constcast** [comment] 2015-11-25 16:55
In my case there really seems to be an installation problem. The error messages disappear when I checkout the development version of gmaps and perform an 

    python setup.py install_data

as the user that wants to run ipython notebook. This steps puts a copy of the JS code to my local ipython installation. A global pip install does not work for me.

**Comment by pbugnion** [comment] 2015-11-26 11:38
Hmm -- that's interesting. Thanks very much for putting the hard work in to solve this. I feel like we might be getting somewhere. Let me get this straight. The following doesn't work:

1. `pip install gmaps` (version 0.1.6?)

But the following does:

1. `git clone gmaps` (what commit?)
2. `cd gmaps`
3. `python setup.py develop`
4. `python setup.py install_data`

Is that correct?

**Comment by constcast** [comment] 2015-11-29 16:33
I need to at least perform the install_data step. The reason for this seems to be the following:

If I run pip install as user root (not via sudo but after a su), then the nbextension is installed to 

    /root/.ipython/nbextensions/gmaps_js/heatmap_view.js

and is not available as my normal user. When I then try to run gmaps as my normal user, the JS file is not available. When I perform a python setup.py install_data with my normal user, then the missing JavaScript file is installed and the error disappears.

**Comment by pbugnion** [comment] 2015-11-29 17:28
Well spotted: this problem will also apply on any multi-tenancy system:

If a user installs `gmaps` system-wide with `pip install gmaps`, this will install the views in his own `.ipython/nbextensions` directory, rather than system-wide.

The temporary solutions are:

Either:
 - Install IPython and gmaps in the same virtual environment.
Or:
 - Every new user wishing to use `gmaps` should download `gmaps` themselves and run `python setup.py install_data`.

**Comment by pbugnion** [comment] 2015-11-29 17:28
For a more permanent fix, we will need to fix the `setup.py` file. The installation should happen system-wide, rather than per-user. I think this might be a matter of replacing `from jupyter_core.paths import jupyter_data_dir` with the path to the system-wide installation of ipython.

**Comment by anrivel** [comment] 2015-12-02 03:57
Not sure if this is related (since I have the same symptoms "IPython does not display the map" using the same example code. 

When importing gmaps, I get:

import gmaps
/home/aj/miniconda/lib/python2.7/site-packages/IPython/html.py:14: ShimWarning: The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.  "`IPython.html.widgets` has moved to `ipywidgets`.", ShimWarning)
/home/aj/miniconda/lib/python2.7/site-packages/IPython/utils/traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")

Javascript error adding output!
TypeError: IPython.load_extensions is not a function
See your browser Javascript console for more details.
python setup.py install_data'

Installed gmaps Dec. 1st, 2015 via PIP. 
Python 2.7.10
gmaps 0.1.6
Have Anaconda

**Comment by pbugnion** [comment] 2015-12-02 08:59
Thanks for the feedback.

This is unrelated -- the version on Pypi (which you installed via pip) does not support IPython 4.0. You have to install from source for IPython 4.0. There were quite a few changes to the underlying IPython architecture from 3.x to 4.0, so migrating has been a non trivial change.

We are planning to release v0.2 on PIP, which will support IPython 4.0.

**Comment by anrivel** [comment] 2015-12-02 18:28
Excellent. Thanks.

**Comment by YairMazor** [comment] 2015-12-21 12:30
Hi,

Basically the same problem as anrivel presented (we are running the same versions of IPython, conda, python, etc.)

I tried to remove the pip installation, then installed from source, and copied the js:
~/anaconda/bin/jupyter-nbextension install gmaps/js
anaconda/gmaps/gmaps/js/gmaps_views.js -> /usr/local/share/jupyter/nbextensions/js/gmaps_views.js

After doing this, I still get the compatibility messages anirvel mentioned.
Any fix for this?

Thanks for your work.

**Comment by pbugnion** [comment] 2015-12-21 15:52
Hi, 

Thanks for the feedback. 

I'm confused by the warning. In the current version of the source, there is no call to `IPython.html.widgets`, for instance. Are you sure that you have purged `gmaps` completely? What output do you get when you type:

    >>> import gmaps
    >>> gmaps.__version__
    (should be 0.2.0-dev)

**Comment by YairMazor** [comment] 2015-12-21 16:16
Thanks for replying so quickly. 
You were right - the running version was indeed 0.1.6.
I repeated the process and restarted the Jupyter server and it now works properly.
Thanks again.

**Comment by Waffleboy** [comment] 2016-02-08 15:37
Heya,

Im using anaconda 2.5,ipython 4.0.3, spyder 2.3.8.

when i do gmaps.display(maps). i get:

**Comment by pbugnion** [comment] 2016-02-08 17:18
Can you post an entire code snippet?

**Comment by Waffleboy** [comment] 2016-02-09 06:28
Thanks for your quick reply! :)

`import pandas as pd
import gmaps
import numpy as np
#preprocessing
df=pd.read_csv('C:/Users/Thiru/Desktop/gtd_2011to2014.csv',encoding='cp1252',low_memory=False)
df=df[df['gname']!='Unknown']
df = df[pd.notnull(df['latitude'])]
df = df[pd.notnull(df['longitude'])]
df = df.reset_index()

lat = df['latitude']
long = df['longitude']
target=df['gname']

#append lat long as tuple to attacks. Form: (lat,long)
attacks = []

for i in range(len(df)):
    if target[i] == 'Huthis': #try it on one particular group
        attacks.append((lat[i],long[i]))
        
data = np.asarray(attacks) #convert attacks to numpy array
maps = gmaps.heatmap(data)
gmaps.display(maps)`
 #nothing happens. only a IPython.core.display.Javascript object is returned

**Comment by pbugnion** [comment] 2016-02-09 10:07
This looks good to me (a priori). Do the examples work? What happens if you follow [this example](http://pascalbugnion.net/code.html#gmaps)?

Also, what errors do you get if you:
1. Open a fresh notebook
2. Open the browser javascript console
3. Run your example

**Comment by Waffleboy** [comment] 2016-02-09 11:37
At the 

`gmaps.datasets.load_dataset('taxi_rides')`
part, it gives

`TypeError: the JSON object must be str, not 'bytes'`

This is what happens when i run with ipython anaconda
![image](https://cloud.githubusercontent.com/assets/12254813/12915183/62b5d132-cf64-11e5-83d0-1bddea8f4632.png)

and this is what happens with jupyter qtconsole
![image](https://cloud.githubusercontent.com/assets/12254813/12915195/873a2c7e-cf64-11e5-8e2e-9d96a44303d6.png)

**Comment by pbugnion** [comment] 2016-02-09 14:04
This is supposed to work in an IPython notebook -- it definitely won't work in the console or the terminal.

**Comment by Waffleboy** [comment] 2016-02-10 03:28
Sorry if i wasnt clear, Its the same on the notebook - i tried those after the notebook.

![image](https://cloud.githubusercontent.com/assets/12254813/12938000/66b3f1e4-cfe9-11e5-91c1-53a965ae0c6b.png)

![image](https://cloud.githubusercontent.com/assets/12254813/12938006/6f6b3cf2-cfe9-11e5-821a-339bb6ead4c2.png)

**Comment by pbugnion** [comment] 2016-02-11 08:54
It looks like something went wrong with the installation -- when I have a bit of time, I intend to overhaul the entire installation procedure.

Since the examples are not working, I suggest you work off the following input:

    In [1]: import gmaps
    In [2]: data = [ [1.,10.], [2., 20.], [3.,30.] ] # latitude, longitude pairs
              gmaps.heatmap(data)

... you should get three points plotted in Africa.

To fix the installation open an ipython shell or notebook and type:

```
from jupyter_core.paths import jupyter_data_dir
jupyter_data_dir()
```

... a directory name should be printed. If you look inside that directory, there should be a `nbextensions` directory. Inside that directory there should be a `gmaps_js` folder with a single file, `gmaps_views.js`. If the `gmaps_js` directory is missing, create it and, inside that, create `gmaps_views.js`. Get the contents of `gmaps_views.js` directly from the source code (e.g. from [here](https://raw.githubusercontent.com/pbugnion/gmaps/master/gmaps/js/gmaps_views.js)).

**Comment by JoshuaC3** [comment] 2016-04-27 11:42
This fix did not work for me. I ran the code
`from jupyter_core.paths import jupyter_data_dir
jupyter_data_dir()` 
but there was not `nbextension` within there. I created one and added that other stuff but to no avail. Is there another location I should be looking?

**Comment by soedr** [comment] 2016-05-30 17:58
Hi, thank you for all the hard work making this available. 

Sorry to add to this, but am not able to get any output at all and did not find `nbextension` in the directory listed by

`from jupyter_core.paths import jupyter_data_dir
jupyter_data_dir()`

I am running anaconda 4.05, jupyter 4, python 3.5.

Any idea what might have happened and how to fix it?

**Comment by pbugnion** [comment] 2016-06-01 14:53
Are you running jupyter 4.2? 

Unfortunately, the interface for installing new extensions in jupyter 4.2 has changed completely so it has completely broken the installation process. I'm currently working on a fix.

**Comment by JoshuaC3** [comment] 2016-06-01 14:56
I do not think so
```
jupyter                   1.0.0                    py35_1    defaults
jupyter-client            4.1.1                     <pip>
jupyter-console           4.0.3                     <pip>
jupyter-core              4.0.6                     <pip>
jupyter_client            4.1.1                    py35_0    defaults
jupyter_console           4.0.3                    py35_0    defaults
jupyter_core              4.0.6                    py35_0    defaults
```

**Comment by pbugnion** [comment] 2016-06-02 06:03
If you open your browser's JavaScript console when you run `gmaps.plainmap()` or `gmaps.heatmap(...)`, do you get an error like this:

```
Failed to load extensions:
Error: Script error for "widgets/js/widget", needed by: nbextensions/gmaps_js/gmaps_views http://requirejs.org/docs/errors.html#scripterror
```

If so, that's to do with the changes underlying how jupyter loads extensions, which I'm currently working to fix.

Otherwise, you should be able to take all the code in the file `gmaps/js/gmaps_views.js` and paste it in a JavaScript shell magic. Write this in a cell somewhere near the top of the notebook:

```
%% javascript

[ paste code here ]
```

You should be able to use the `gmaps` code normally after that.

**Comment by JoshuaC3** [comment] 2016-06-02 09:03
I get no error now. It displays the gmaps  'gmaps.plainmap()' and 'gmaps.heatmap(...)'.

I have not updated any gmaps stuff since April the 27th, when I last posted. It could be that something else has updated since then? If there is any further information you want that might be helpful then let me know. Regards, Confused but happy.

**Comment by pbugnion** [comment] 2016-06-02 13:28
There has been no change since -- I've been (occasionally) working on an installation fix offline since then. 

Glad it's working either way.

**Comment by pbugnion** [comment] 2016-06-15 06:00
The 0.3.0 release uses the new Jupyter nbextension mechanism for installing gmaps. All the problems mentioned here are not relevant any more.

Closing this to avoid confusion.

**Closed by pbugnion** 2016-06-15 06:00 UTC

**Comment by ancago** [comment] 2018-11-12 20:36
and how to display a figure (map) e.g. in Pycharm, not in Jupiter...?

**Comment by pbugnion** [comment] 2018-11-13 06:38
> and how to display a figure (map) e.g. in Pycharm, not in Jupiter...?

Thanks for raising this. To make issues more discoverable for other users, please open a separate issue if it's not related to this.

**Comment by lumindak** [comment] 2020-04-14 14:00
> Running the following code does not produce any output on Ipython Notebook v3.2.0 and Python 2.7.10
> 
> ```
> import gmaps
> 
> data = [ [ 37.782551,-122.445368 ],
>          [ 37.782745,-122.444586 ],
>          [ 37.782842,-122.443858 ] ]
> 
> gmaps.heatmap(data)
> ```
> 
> No Warnings (except for
> `:0: FutureWarning: IPython widgets are experimental and may change in the future`.) and No Errors.

I had the same error in jupyter lab. Using jupyter notebook solved it.
