### ISSUE TITLE
Building gmaps on jupyterLab changes background color on all output cells

### ISSUE THREAD

**Issue by nonsignificantp** [pbugnion/gmaps#265] opened 2018-09-16 17:11 UTC
After building gmaps on jupyterLab, all output cells on the notebook changed their background colors from white to grey. This is not only bothering, but also disrupts the readability when using dark themes.

Unbuilding gmaps corrected the error immediately.

**Comment by pbugnion** [comment] 2018-09-19 18:29
Thanks for raising this. I can't seem to reproduce this. What version of JupyterLab are you using?

**Comment by pbugnion** [comment] 2018-09-23 12:34
Thanks -- I managed to reproduce this. The issue is that we load the Twitter Bootstrap CSS in the JupyterLab plugin [*]. Bootstrap redefines what a `pre` should look like, overriding the JupyterLab default CSS. The fix is to remove the dependency on Bootstrap. Progress on this is tracked in PR #265.

[*] jupyter-gmaps was initially developed for notebooks, before JupyterLab existed. Notebooks ship with Bootstrap, so it made sense to take advantage of that. When porting to JupyterLab, the easiest way to avoid having things look completely off was to include Bootstrap.

**Comment by pbugnion** [comment] 2018-09-26 06:55
The fix for this is released in gmaps 0.8.1, available on Pypi right now and from conda-forge in the next 24 hours or so.

**Closed by pbugnion** 2018-09-26 06:55 UTC
