### ISSUE TITLE
gmaps not working in Chrome version Version 74.0.3729.131 (Official Build) (64-bit) or latest Firefox Version

### ISSUE THREAD

**Issue by rlemm-pan** [pbugnion/gmaps#303] opened 2019-05-08 02:56 UTC
After upgrading to Chrome Version 74.0.3729.131 (Official Build) (64-bit), gmaps quit displaying maps.  Verified by trying on previous version of chrome.  Also tried on latest version of Firefox.  Safari works and so does Microsoft Edge.

**Comment by pbugnion** [comment] 2019-05-16 06:42
Thanks for raising this.

I cannot reproduce this at all using Chrome 74.0.3729.131 on MacOS. The map loads fine.

Does the browser console show any errors?

**Comment by pbugnion** [comment] 2019-07-20 07:38
Closing this as unable to reproduce. Feel free to re-open if this is still an issue.

**Closed by pbugnion** 2019-07-20 07:38 UTC
