### ISSUE TITLE
Exception error when exporting to HTML

### ISSUE THREAD

**Issue by picaguo1997** [pbugnion/gmaps#298] opened 2019-03-16 00:14 UTC
Hello, 

I tried exporting my map to HTML, the code is same in the documentation.
`embed_minimal_html('export.html', views=[fig])`
It works fine on my computer, but my friend has encountered the following exception error.
<img width="982" alt="error" src="https://user-images.githubusercontent.com/34975332/54467860-d38d6f80-47c2-11e9-80ae-b05dc33c9a67.png">

I am afraid we forget to do something before running the code.
What can I do to fix this?

Thank you for your help!
Best, 
Iris

**Comment by pbugnion** [comment] 2019-03-16 07:28
Thanks for raising this. This is a duplicate of #284. I suggest tracking that.

**Comment by pbugnion** [comment] 2019-03-16 07:29
Closing this, but feel free to re-open if you think I'm mistaken.

**Closed by pbugnion** 2019-03-16 07:28 UTC
